server:
  replicaCount: 1
  image:
    repository: menyus/zv-whisper-server
    tag: latest
  service:
    internalPort: 3000
    externalPort: 8080
    nodePort: 32080

client:
  replicaCount: 3
  image:
    repository: menyus/zv-whisper-client
    tag: latest

main:
  replicaCount: 2
  image:
    repository: menyus/zv-whisper-main
    tag: latest