apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        env:
        - name: REDIS_HOST
          value: "zv-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVER_URL
          value: "http://zv-project-server:3000"