apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        # --- EZT A KÉT SORT ADD HOZZÁ A KONTÉNERHEZ ---
        command: ["/bin/sh", "-c"]
        args:
          - |
            sed -i 's|await sio.connect("http://localhost:3000")|await sio.connect(os.getenv("SERVER_URL", "http://zv-project-server:3000"))|g' /app/client.py 2>/dev/null || sed -i 's|"http://localhost:3000"|os.getenv("SERVER_URL")|g' /app/client.py
            
            python /app/client.py
        # ----------------------------------------------
        env:
        - name: REDIS_HOST
          value: "zv-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVER_URL
          value: "http://zv-project-server:3000"