apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-client
  labels:
    app: {{ .Release.Name }}-client
spec:
  replicas: {{ .Values.client.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-client
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        volumeMounts:
        - name: config-volume
          mountPath: /app/.env
          subPath: env-file
        command: ["/bin/sh", "-c"]
        args:
          - |
            set -a
            . /app/.env
            set +a

            sed -i "s|http://localhost:3000|$SERVER_URL|g" /app/client.py

            python /app/client.py
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config