apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config

data:
  env-file: |
    REDIS_HOST=zv-redis
    REDIS_PORT=6379
    SERVER_HOST=0.0.0.0
    SERVER_PORT=3000
    SERVER_URL=http://{{ .Release.Name }}-server:3000
    MAIN_HOST=0.0.0.0
    MAIN_PORT=5000
    MAIN_DEBUG=False
    LOGFILE=/tmp/log.txt
    SERVER_LOG=/tmp/server.log
    CLIENT_LOG=/tmp/client.log
    MAIN_LOG=/tmp/main.log
    TRANS_LOG=/tmp/trans.log
    WHISPER_MODEL=base