apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-main
  labels:
    app: {{ .Release.Name }}-main
spec:
  replicas: {{ .Values.main.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-main
    spec:
      containers:
      - name: main
        image: "{{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
            - |
              sed -i 's|await sio.connect("http://localhost:3000")|await sio.connect(os.getenv("SERVER_URL", "http://zv-project-server:3000"))|g' /app/main.py 2>/dev/null || sed -i 's|"http://localhost:3000"|os.getenv("SERVER_URL")|g' /app/main.py

              grep -n "SERVER_URL\|localhost:3000\|zv-project-server" /app/main.py

              pip install requests

              python /app/main.py
        env:
        - name: REDIS_HOST
          value: "zv-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVER_URL
          value: "http://zv-project-server:3000"