apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-main
  labels:
    app: {{ .Release.Name }}-main
spec:
  replicas: {{ .Values.main.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-main
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-main
    spec:
      containers:
      - name: main
        image: "{{ .Values.main.image.repository }}:{{ .Values.main.image.tag }}"
        command: ["/bin/sh", "-c"]
        args:
        - |
          pip install requests && python /app/main.py
        env:
        - name: REDIS_HOST
          value: "zv-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVER_URL
          value: "http://zv-project-server:8080"