apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}-server
spec:
  replicas: {{ .Values.server.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-server
    spec:
      containers:
      - name: server
        image: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
        ports:
        - containerPort: {{ .Values.server.service.internalPort }}
        env:
        - name: SERVER_HOST
          value: "0.0.0.0"
        - name: SERVER_PORT
          value: "{{ .Values.server.service.internalPort }}"
        - name: REDIS_HOST
          value: "zv-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: SERVER_LOG
          value: "/tmp/server.log"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-server
  ports:
    - name: http
      port: 3000
      targetPort: {{ .Values.server.service.internalPort }}
      protocol: TCP