apiVersion: v1
kind: Service
metadata:
  name: zv-project-server
  labels:
    app: zv-project-server
spec:
  selector:
    app: zv-project-server
  ports:
    - name: http
      port: 3000
      targetPort: 3000